left_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "body_left_wheel_joint"

right_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: "body_right_wheel_joint"